import React from "react";
import style from "./page.module.css";
import Image from "next/image";
import Button from "@/components/Button/Button";

const URL_IMG =
  "https://images.pexels.com/photos/3380361/pexels-photo-3380361.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2";

export const metadata = {
  title: "Lamamia - About",
  description: "Generated by create next app",
};

const About = () =>
{
  return (
    <>
      <div className={style.imgContainer}>
        <Image
          src={URL_IMG}
          fill={true}
          className={style.img}
          alt="img background"
        />
        <div className={style.textImg}>
          <h1 className={style.imgTitle}>Reprehenderit consequat.</h1>
          <h2 className={style.imgDesc}>
            {" "}
            et tempor dolore adipisicing officia.
          </h2>
        </div>
      </div>
      <div className={style.textContainer}>
        <div className={style.item}>
          <h1 className={style.title}>Who are we?</h1>
          <p className={style.desc}>
            Esse ut sint sint fugiat. Lorem voluptate proident sint elit velit
            reprehenderit consectetur incididunt quis ad irure enim aute.
            <br />
            Sunt ut enim exercitation voluptate ex amet ex ut nulla pariatur
            quis culpa tempor. Adipisicing consequat tempor nisi ut excepteur
            proident deserunt nostrud sint qui excepteur eu.
          </p>
        </div>
        <div className={style.item}>
          <h1 className={style.title}>What we do?</h1>
          <p className={style.desc}>
            Ad ipsum occaecat tempor culpa do veniam. Consectetur sint eiusmod
            deserunt qui pariatur enim duis Lorem aute. Nulla ipsum ipsum culpa
            veniam qui ad eu adipisicing deserunt.
          </p>
          <Button text={"Contact"} url={"/contact"} />
        </div>
      </div>
    </>
  );
};

export default About;